PUSH -> Fix typescript :) -> Added more workflows -> Braindead

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -1,23 +1,19 @@
-name: Node.js CI
+name: Frontend Jobs
 
 on: [push, pull_request]
 jobs:
   build:
     name: Frontend Build
     runs-on: ubuntu-latest
-    
     permissions:
       contents: read
-    
     strategy:
       fail-fast: false
       matrix:
         node-version: [20]
-    
     defaults:
       run:
         working-directory: frontend
-
     steps:
       - name: Code Checkout
         uses: actions/checkout@v4
@@ -35,3 +31,61 @@ jobs:
           fi
       - name: Build
         run: yarn build
+  lint:
+    name: Frontend Lint
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    strategy:
+      fail-fast: false
+      matrix:
+        node-version: [20]
+    defaults:
+      run:
+        working-directory: frontend
+    steps:
+      - name: Code Checkout
+        uses: actions/checkout@v4
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v2
+        with:
+          node-version: ${{ matrix.node-version }}
+      - name: Install dependencies
+        run: |
+          if [ -f yarn.lock ]; then
+            yarn install --frozen-lockfile
+          else
+            echo "yarn.lock file not found"
+            exit 1
+          fi
+      - name: Lint
+        run: yarn lint
+  format:
+    name: Frontend Format
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    strategy:
+      fail-fast: false
+      matrix:
+        node-version: [20]
+    defaults:
+      run:
+        working-directory: frontend
+    steps:
+      - name: Code Checkout
+        uses: actions/checkout@v4
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v2
+        with:
+          node-version: ${{ matrix.node-version }}
+      - name: Install dependencies
+        run: |
+          if [ -f yarn.lock ]; then
+            yarn install --frozen-lockfile
+          else
+            echo "yarn.lock file not found"
+            exit 1
+          fi
+      - name: Format
+        run: yarn format
